/**
 * Payload specs module TK_plugin
 *
 * Generated by lpldgen 1.4.6
 */

#include "pld_tk_plugin.h"
#include <payloads_internal.h>

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SET_TIME_REQ_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SET_TIME_REQ **output) {
    pld_log_trace("TK_plugin_TK_SET_TIME_REQ_parse");
    if (length != TK_PLUGIN_TK_SET_TIME_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct TK_plugin_TK_SET_TIME_REQ *data = alloc(TK_PLUGIN_TK_SET_TIME_REQ_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return TK_plugin_TK_SET_TIME_REQ_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SET_TIME_REQ_parse_s(const uint8_t * bytes, const size_t length, struct TK_plugin_TK_SET_TIME_REQ *output) {
    pld_log_trace("TK_plugin_TK_SET_TIME_REQ_parse_s");
    uint64_t tmp64 = 0;
    if (length != TK_PLUGIN_TK_SET_TIME_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = TK_PLUGIN_TK_SET_TIME_REQ_ID;
    
    /* parsing */
    bytes++;
    
    tmp64 = 0;
    tmp64 |= (uint64_t) *bytes++ << 56;
    tmp64 |= (uint64_t) *bytes++ << 48;
    tmp64 |= (uint64_t) *bytes++ << 40;
    tmp64 |= (uint64_t) *bytes++ << 32;
    tmp64 |= (uint64_t) *bytes++ << 24;
    tmp64 |= (uint64_t) *bytes++ << 16;
    tmp64 |= (uint64_t) *bytes++ << 8;
    tmp64 |= (uint64_t) *bytes;
    output->time = (uint64_t)(tmp64);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SET_TIME_RSP_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SET_TIME_RSP **output) {
    pld_log_trace("TK_plugin_TK_SET_TIME_RSP_parse");
    if (length != TK_PLUGIN_TK_SET_TIME_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct TK_plugin_TK_SET_TIME_RSP *data = alloc(TK_PLUGIN_TK_SET_TIME_RSP_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return TK_plugin_TK_SET_TIME_RSP_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SET_TIME_RSP_parse_s(const uint8_t * bytes, const size_t length, struct TK_plugin_TK_SET_TIME_RSP *output) {
    pld_log_trace("TK_plugin_TK_SET_TIME_RSP_parse_s");
    if (length != TK_PLUGIN_TK_SET_TIME_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = TK_PLUGIN_TK_SET_TIME_RSP_ID;
    
    /* parsing */
    bytes++;
    
    output->ret_val = (uint8_t)(*bytes);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_GET_TIME_REQ_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_GET_TIME_REQ **output) {
    pld_log_trace("TK_plugin_TK_GET_TIME_REQ_parse");
    if (length != TK_PLUGIN_TK_GET_TIME_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct TK_plugin_TK_GET_TIME_REQ *data = alloc(TK_PLUGIN_TK_GET_TIME_REQ_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return TK_plugin_TK_GET_TIME_REQ_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_GET_TIME_REQ_parse_s(const uint8_t * bytes, const size_t length, struct TK_plugin_TK_GET_TIME_REQ *output) {
    pld_log_trace("TK_plugin_TK_GET_TIME_REQ_parse_s");
    if (length != TK_PLUGIN_TK_GET_TIME_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = TK_PLUGIN_TK_GET_TIME_REQ_ID;
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_GET_TIME_RSP_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_GET_TIME_RSP **output) {
    pld_log_trace("TK_plugin_TK_GET_TIME_RSP_parse");
    if (length != TK_PLUGIN_TK_GET_TIME_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct TK_plugin_TK_GET_TIME_RSP *data = alloc(TK_PLUGIN_TK_GET_TIME_RSP_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return TK_plugin_TK_GET_TIME_RSP_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_GET_TIME_RSP_parse_s(const uint8_t * bytes, const size_t length, struct TK_plugin_TK_GET_TIME_RSP *output) {
    pld_log_trace("TK_plugin_TK_GET_TIME_RSP_parse_s");
    uint64_t tmp64 = 0;
    if (length != TK_PLUGIN_TK_GET_TIME_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = TK_PLUGIN_TK_GET_TIME_RSP_ID;
    
    /* parsing */
    bytes++;
    
    tmp64 = 0;
    tmp64 |= (uint64_t) *bytes++ << 56;
    tmp64 |= (uint64_t) *bytes++ << 48;
    tmp64 |= (uint64_t) *bytes++ << 40;
    tmp64 |= (uint64_t) *bytes++ << 32;
    tmp64 |= (uint64_t) *bytes++ << 24;
    tmp64 |= (uint64_t) *bytes++ << 16;
    tmp64 |= (uint64_t) *bytes++ << 8;
    tmp64 |= (uint64_t) *bytes;
    output->time = (uint64_t)(tmp64);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SYNC_TIME_REQ_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SYNC_TIME_REQ **output) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_REQ_parse");
    if (length != TK_PLUGIN_TK_SYNC_TIME_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct TK_plugin_TK_SYNC_TIME_REQ *data = alloc(TK_PLUGIN_TK_SYNC_TIME_REQ_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return TK_plugin_TK_SYNC_TIME_REQ_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SYNC_TIME_REQ_parse_s(const uint8_t * bytes, const size_t length, struct TK_plugin_TK_SYNC_TIME_REQ *output) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_REQ_parse_s");
    uint64_t tmp64 = 0;
    if (length != TK_PLUGIN_TK_SYNC_TIME_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = TK_PLUGIN_TK_SYNC_TIME_REQ_ID;
    
    /* parsing */
    bytes++;
    
    tmp64 = 0;
    tmp64 |= (uint64_t) *bytes++ << 56;
    tmp64 |= (uint64_t) *bytes++ << 48;
    tmp64 |= (uint64_t) *bytes++ << 40;
    tmp64 |= (uint64_t) *bytes++ << 32;
    tmp64 |= (uint64_t) *bytes++ << 24;
    tmp64 |= (uint64_t) *bytes++ << 16;
    tmp64 |= (uint64_t) *bytes++ << 8;
    tmp64 |= (uint64_t) *bytes++;
    output->frequency = ((x64_t){ .u=(tmp64) }).i;
    
    output->flags = (uint8_t)(*bytes);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SYNC_TIME_RSP_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SYNC_TIME_RSP **output) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_RSP_parse");
    if (length != TK_PLUGIN_TK_SYNC_TIME_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct TK_plugin_TK_SYNC_TIME_RSP *data = alloc(TK_PLUGIN_TK_SYNC_TIME_RSP_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return TK_plugin_TK_SYNC_TIME_RSP_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SYNC_TIME_RSP_parse_s(const uint8_t * bytes, const size_t length, struct TK_plugin_TK_SYNC_TIME_RSP *output) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_RSP_parse_s");
    uint64_t tmp64 = 0;
    if (length != TK_PLUGIN_TK_SYNC_TIME_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = TK_PLUGIN_TK_SYNC_TIME_RSP_ID;
    
    /* parsing */
    bytes++;
    
    output->error = (uint8_t)(*bytes++);
    
    tmp64 = 0;
    tmp64 |= (uint64_t) *bytes++ << 56;
    tmp64 |= (uint64_t) *bytes++ << 48;
    tmp64 |= (uint64_t) *bytes++ << 40;
    tmp64 |= (uint64_t) *bytes++ << 32;
    tmp64 |= (uint64_t) *bytes++ << 24;
    tmp64 |= (uint64_t) *bytes++ << 16;
    tmp64 |= (uint64_t) *bytes++ << 8;
    tmp64 |= (uint64_t) *bytes++;
    output->last_sync = (uint64_t)(tmp64);
    
    output->mode = (uint8_t)(*bytes++);
    
    output->master_node = (uint8_t)(*bytes++);
    
    output->last_failed_node = (uint8_t)(*bytes++);
    
    output->ret_val = (uint8_t)(*bytes);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SYNC_SLAVES_REQ_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SYNC_SLAVES_REQ **output) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_REQ_parse");
    if (length != TK_PLUGIN_TK_SYNC_SLAVES_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct TK_plugin_TK_SYNC_SLAVES_REQ *data = alloc(TK_PLUGIN_TK_SYNC_SLAVES_REQ_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return TK_plugin_TK_SYNC_SLAVES_REQ_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SYNC_SLAVES_REQ_parse_s(const uint8_t * bytes, const size_t length, struct TK_plugin_TK_SYNC_SLAVES_REQ *output) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_REQ_parse_s");
    uint64_t tmp64 = 0;
    if (length != TK_PLUGIN_TK_SYNC_SLAVES_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID;
    
    /* parsing */
    bytes++;
    
    output->node = (uint8_t)(*bytes++);
    
    tmp64 = 0;
    tmp64 |= (uint64_t) *bytes++ << 56;
    tmp64 |= (uint64_t) *bytes++ << 48;
    tmp64 |= (uint64_t) *bytes++ << 40;
    tmp64 |= (uint64_t) *bytes++ << 32;
    tmp64 |= (uint64_t) *bytes++ << 24;
    tmp64 |= (uint64_t) *bytes++ << 16;
    tmp64 |= (uint64_t) *bytes++ << 8;
    tmp64 |= (uint64_t) *bytes;
    output->time = (uint64_t)(tmp64);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SYNC_SLAVES_RSP_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SYNC_SLAVES_RSP **output) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_RSP_parse");
    if (length != TK_PLUGIN_TK_SYNC_SLAVES_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct TK_plugin_TK_SYNC_SLAVES_RSP *data = alloc(TK_PLUGIN_TK_SYNC_SLAVES_RSP_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return TK_plugin_TK_SYNC_SLAVES_RSP_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SYNC_SLAVES_RSP_parse_s(const uint8_t * bytes, const size_t length, struct TK_plugin_TK_SYNC_SLAVES_RSP *output) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_RSP_parse_s");
    if (length != TK_PLUGIN_TK_SYNC_SLAVES_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID;
    
    /* parsing */
    bytes++;
    
    output->ret_val = (uint8_t)(*bytes);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SET_TIME_REQ_build(const struct TK_plugin_TK_SET_TIME_REQ * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("TK_plugin_TK_SET_TIME_REQ_build");
    const size_t byte_size = TK_PLUGIN_TK_SET_TIME_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SET_TIME_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SET_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SET_TIME_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SET_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return TK_plugin_TK_SET_TIME_REQ_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SET_TIME_REQ_build_s(const struct TK_plugin_TK_SET_TIME_REQ * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("TK_plugin_TK_SET_TIME_REQ_build_s");
    uint64_t tmp64 = 0;
    const size_t byte_size = TK_PLUGIN_TK_SET_TIME_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SET_TIME_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SET_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SET_TIME_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SET_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x00;
    
    tmp64 = (uint64_t)(data->time);
    *output++ = (uint8_t) ((tmp64 >> 56) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 48) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 40) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 32) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 24) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 16) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 8) & 0xff);
    *output++ = (uint8_t) (tmp64 & 0xff);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SET_TIME_RSP_build(const struct TK_plugin_TK_SET_TIME_RSP * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("TK_plugin_TK_SET_TIME_RSP_build");
    const size_t byte_size = TK_PLUGIN_TK_SET_TIME_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SET_TIME_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SET_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SET_TIME_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SET_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return TK_plugin_TK_SET_TIME_RSP_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SET_TIME_RSP_build_s(const struct TK_plugin_TK_SET_TIME_RSP * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("TK_plugin_TK_SET_TIME_RSP_build_s");
    const size_t byte_size = TK_PLUGIN_TK_SET_TIME_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SET_TIME_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SET_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SET_TIME_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SET_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x00;
    
    *output++ = (uint8_t)(data->ret_val);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_GET_TIME_REQ_build(const struct TK_plugin_TK_GET_TIME_REQ * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("TK_plugin_TK_GET_TIME_REQ_build");
    const size_t byte_size = TK_PLUGIN_TK_GET_TIME_REQ_BIN_SIZE;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_GET_TIME_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_GET_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_GET_TIME_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_GET_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return TK_plugin_TK_GET_TIME_REQ_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_GET_TIME_REQ_build_s(const struct TK_plugin_TK_GET_TIME_REQ * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("TK_plugin_TK_GET_TIME_REQ_build_s");
    const size_t byte_size = TK_PLUGIN_TK_GET_TIME_REQ_BIN_SIZE;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_GET_TIME_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_GET_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_GET_TIME_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_GET_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x01;
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_GET_TIME_RSP_build(const struct TK_plugin_TK_GET_TIME_RSP * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("TK_plugin_TK_GET_TIME_RSP_build");
    const size_t byte_size = TK_PLUGIN_TK_GET_TIME_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_GET_TIME_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_GET_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_GET_TIME_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_GET_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return TK_plugin_TK_GET_TIME_RSP_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_GET_TIME_RSP_build_s(const struct TK_plugin_TK_GET_TIME_RSP * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("TK_plugin_TK_GET_TIME_RSP_build_s");
    uint64_t tmp64 = 0;
    const size_t byte_size = TK_PLUGIN_TK_GET_TIME_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_GET_TIME_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_GET_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_GET_TIME_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_GET_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x01;
    
    tmp64 = (uint64_t)(data->time);
    *output++ = (uint8_t) ((tmp64 >> 56) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 48) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 40) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 32) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 24) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 16) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 8) & 0xff);
    *output++ = (uint8_t) (tmp64 & 0xff);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SYNC_TIME_REQ_build(const struct TK_plugin_TK_SYNC_TIME_REQ * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_REQ_build");
    const size_t byte_size = TK_PLUGIN_TK_SYNC_TIME_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SYNC_TIME_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SYNC_TIME_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return TK_plugin_TK_SYNC_TIME_REQ_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SYNC_TIME_REQ_build_s(const struct TK_plugin_TK_SYNC_TIME_REQ * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_REQ_build_s");
    uint64_t tmp64 = 0;
    const size_t byte_size = TK_PLUGIN_TK_SYNC_TIME_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SYNC_TIME_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SYNC_TIME_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x02;
    
    tmp64 = ((x64_t){ .i=(data->frequency) }).u;
    *output++ = (uint8_t) ((tmp64 >> 56) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 48) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 40) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 32) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 24) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 16) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 8) & 0xff);
    *output++ = (uint8_t) (tmp64 & 0xff);
    
    *output++ = (uint8_t)(data->flags);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SYNC_TIME_RSP_build(const struct TK_plugin_TK_SYNC_TIME_RSP * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_RSP_build");
    const size_t byte_size = TK_PLUGIN_TK_SYNC_TIME_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SYNC_TIME_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SYNC_TIME_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return TK_plugin_TK_SYNC_TIME_RSP_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SYNC_TIME_RSP_build_s(const struct TK_plugin_TK_SYNC_TIME_RSP * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_RSP_build_s");
    uint64_t tmp64 = 0;
    const size_t byte_size = TK_PLUGIN_TK_SYNC_TIME_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SYNC_TIME_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SYNC_TIME_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x02;
    
    *output++ = (uint8_t)(data->error);
    
    tmp64 = (uint64_t)(data->last_sync);
    *output++ = (uint8_t) ((tmp64 >> 56) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 48) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 40) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 32) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 24) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 16) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 8) & 0xff);
    *output++ = (uint8_t) (tmp64 & 0xff);
    
    *output++ = (uint8_t)(data->mode);
    
    *output++ = (uint8_t)(data->master_node);
    
    *output++ = (uint8_t)(data->last_failed_node);
    
    *output++ = (uint8_t)(data->ret_val);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SYNC_SLAVES_REQ_build(const struct TK_plugin_TK_SYNC_SLAVES_REQ * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_REQ_build");
    const size_t byte_size = TK_PLUGIN_TK_SYNC_SLAVES_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return TK_plugin_TK_SYNC_SLAVES_REQ_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SYNC_SLAVES_REQ_build_s(const struct TK_plugin_TK_SYNC_SLAVES_REQ * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_REQ_build_s");
    uint64_t tmp64 = 0;
    const size_t byte_size = TK_PLUGIN_TK_SYNC_SLAVES_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x03;
    
    *output++ = (uint8_t)(data->node);
    
    tmp64 = (uint64_t)(data->time);
    *output++ = (uint8_t) ((tmp64 >> 56) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 48) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 40) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 32) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 24) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 16) & 0xff);
    *output++ = (uint8_t) ((tmp64 >> 8) & 0xff);
    *output++ = (uint8_t) (tmp64 & 0xff);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t TK_plugin_TK_SYNC_SLAVES_RSP_build(const struct TK_plugin_TK_SYNC_SLAVES_RSP * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_RSP_build");
    const size_t byte_size = TK_PLUGIN_TK_SYNC_SLAVES_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return TK_plugin_TK_SYNC_SLAVES_RSP_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t TK_plugin_TK_SYNC_SLAVES_RSP_build_s(const struct TK_plugin_TK_SYNC_SLAVES_RSP * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_RSP_build_s");
    const size_t byte_size = TK_PLUGIN_TK_SYNC_SLAVES_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x03;
    
    *output++ = (uint8_t)(data->ret_val);
    
    return PLD_OK;
}

/** Test constants in a "TK_SET_TIME_REQ" payload */
static bool TK_plugin_TK_SET_TIME_REQ_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x00);
}

/** Test constants in a "TK_SET_TIME_RSP" payload */
static bool TK_plugin_TK_SET_TIME_RSP_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x00);
}

/** Test constants in a "TK_GET_TIME_REQ" payload */
static bool TK_plugin_TK_GET_TIME_REQ_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x01);
}

/** Test constants in a "TK_GET_TIME_RSP" payload */
static bool TK_plugin_TK_GET_TIME_RSP_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x01);
}

/** Test constants in a "TK_SYNC_TIME_REQ" payload */
static bool TK_plugin_TK_SYNC_TIME_REQ_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x02);
}

/** Test constants in a "TK_SYNC_TIME_RSP" payload */
static bool TK_plugin_TK_SYNC_TIME_RSP_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x02);
}

/** Test constants in a "TK_SYNC_SLAVES_REQ" payload */
static bool TK_plugin_TK_SYNC_SLAVES_REQ_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x03);
}

/** Test constants in a "TK_SYNC_SLAVES_RSP" payload */
static bool TK_plugin_TK_SYNC_SLAVES_RSP_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x03);
}

#if PLD_HAVE_EXPORT
#include <inttypes.h>

static pld_error_t TK_plugin_TK_SET_TIME_REQ_to_json_inner(const struct TK_plugin_TK_SET_TIME_REQ *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("TK_plugin_TK_SET_TIME_REQ_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != TK_PLUGIN_TK_SET_TIME_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SET_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->time));
            cJSON_AddItemToObjectCS(output, "time", item0);
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "time", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u64"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->time));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t TK_plugin_TK_SET_TIME_REQ_to_json(const struct TK_plugin_TK_SET_TIME_REQ *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("TK_plugin_TK_SET_TIME_REQ_to_json");
    return pld_to_json_by_spec(PldSpec_TK_plugin_TK_SET_TIME_REQ, data, style, output);
}

static pld_error_t TK_plugin_TK_SET_TIME_RSP_to_json_inner(const struct TK_plugin_TK_SET_TIME_RSP *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("TK_plugin_TK_SET_TIME_RSP_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != TK_PLUGIN_TK_SET_TIME_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SET_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->ret_val));
            cJSON_AddItemToObjectCS(output, "ret_val", item0);
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "ret_val", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->ret_val));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t TK_plugin_TK_SET_TIME_RSP_to_json(const struct TK_plugin_TK_SET_TIME_RSP *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("TK_plugin_TK_SET_TIME_RSP_to_json");
    return pld_to_json_by_spec(PldSpec_TK_plugin_TK_SET_TIME_RSP, data, style, output);
}

static pld_error_t TK_plugin_TK_GET_TIME_REQ_to_json_inner(const struct TK_plugin_TK_GET_TIME_REQ *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("TK_plugin_TK_GET_TIME_REQ_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != TK_PLUGIN_TK_GET_TIME_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_GET_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t TK_plugin_TK_GET_TIME_REQ_to_json(const struct TK_plugin_TK_GET_TIME_REQ *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("TK_plugin_TK_GET_TIME_REQ_to_json");
    return pld_to_json_by_spec(PldSpec_TK_plugin_TK_GET_TIME_REQ, data, style, output);
}

static pld_error_t TK_plugin_TK_GET_TIME_RSP_to_json_inner(const struct TK_plugin_TK_GET_TIME_RSP *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("TK_plugin_TK_GET_TIME_RSP_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != TK_PLUGIN_TK_GET_TIME_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_GET_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->time));
            cJSON_AddItemToObjectCS(output, "time", item0);
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "time", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u64"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->time));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t TK_plugin_TK_GET_TIME_RSP_to_json(const struct TK_plugin_TK_GET_TIME_RSP *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("TK_plugin_TK_GET_TIME_RSP_to_json");
    return pld_to_json_by_spec(PldSpec_TK_plugin_TK_GET_TIME_RSP, data, style, output);
}

static pld_error_t TK_plugin_TK_SYNC_TIME_REQ_to_json_inner(const struct TK_plugin_TK_SYNC_TIME_REQ *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_REQ_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != TK_PLUGIN_TK_SYNC_TIME_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_TIME_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->frequency));
            cJSON_AddItemToObjectCS(output, "frequency", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->flags));
            cJSON_AddItemToObjectCS(output, "flags", item0);
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "frequency", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("i64"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->frequency));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "flags", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->flags));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t TK_plugin_TK_SYNC_TIME_REQ_to_json(const struct TK_plugin_TK_SYNC_TIME_REQ *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_REQ_to_json");
    return pld_to_json_by_spec(PldSpec_TK_plugin_TK_SYNC_TIME_REQ, data, style, output);
}

static pld_error_t TK_plugin_TK_SYNC_TIME_RSP_to_json_inner(const struct TK_plugin_TK_SYNC_TIME_RSP *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_RSP_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != TK_PLUGIN_TK_SYNC_TIME_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_TIME_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->error));
            cJSON_AddItemToObjectCS(output, "error", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->last_sync));
            cJSON_AddItemToObjectCS(output, "last_sync", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->mode));
            cJSON_AddItemToObjectCS(output, "mode", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->master_node));
            cJSON_AddItemToObjectCS(output, "master_node", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->last_failed_node));
            cJSON_AddItemToObjectCS(output, "last_failed_node", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->ret_val));
            cJSON_AddItemToObjectCS(output, "ret_val", item0);
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "error", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->error));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "last_sync", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u64"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->last_sync));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "mode", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->mode));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "master_node", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->master_node));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "last_failed_node", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->last_failed_node));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "ret_val", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->ret_val));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t TK_plugin_TK_SYNC_TIME_RSP_to_json(const struct TK_plugin_TK_SYNC_TIME_RSP *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("TK_plugin_TK_SYNC_TIME_RSP_to_json");
    return pld_to_json_by_spec(PldSpec_TK_plugin_TK_SYNC_TIME_RSP, data, style, output);
}

static pld_error_t TK_plugin_TK_SYNC_SLAVES_REQ_to_json_inner(const struct TK_plugin_TK_SYNC_SLAVES_REQ *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_REQ_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->node));
            cJSON_AddItemToObjectCS(output, "node", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->time));
            cJSON_AddItemToObjectCS(output, "time", item0);
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "node", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->node));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "time", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u64"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->time));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t TK_plugin_TK_SYNC_SLAVES_REQ_to_json(const struct TK_plugin_TK_SYNC_SLAVES_REQ *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_REQ_to_json");
    return pld_to_json_by_spec(PldSpec_TK_plugin_TK_SYNC_SLAVES_REQ, data, style, output);
}

static pld_error_t TK_plugin_TK_SYNC_SLAVES_RSP_to_json_inner(const struct TK_plugin_TK_SYNC_SLAVES_RSP *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_RSP_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->ret_val));
            cJSON_AddItemToObjectCS(output, "ret_val", item0);
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "ret_val", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->ret_val));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t TK_plugin_TK_SYNC_SLAVES_RSP_to_json(const struct TK_plugin_TK_SYNC_SLAVES_RSP *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("TK_plugin_TK_SYNC_SLAVES_RSP_to_json");
    return pld_to_json_by_spec(PldSpec_TK_plugin_TK_SYNC_SLAVES_RSP, data, style, output);
}
#endif

static const struct pld_spec payload_specs[8] = {
    {
        .pld_id = TK_PLUGIN_TK_SET_TIME_REQ_ID,
        .address = {
            .src = 255,
            .sport = 255,
            .dst = 13,
            .dport = 10
        },
        .bin_size = 9,
        .c_size = sizeof(struct TK_plugin_TK_SET_TIME_REQ),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = TK_plugin_TK_SET_TIME_REQ_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) TK_plugin_TK_SET_TIME_REQ_parse,
        .build = (fn_build_t) TK_plugin_TK_SET_TIME_REQ_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) TK_plugin_TK_SET_TIME_REQ_parse_s,
        .build_static = (fn_build_static_t) TK_plugin_TK_SET_TIME_REQ_build_s,
        .name = "TK_plugin_TK_SET_TIME_REQ",
    #if PLD_HAVE_EXPORT
        .descr = "TK set time request",
        .data_to_json = (fn_data_to_json_t) TK_plugin_TK_SET_TIME_REQ_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = TK_PLUGIN_TK_SET_TIME_RSP_ID,
        .address = {
            .src = 13,
            .sport = 10,
            .dst = 255,
            .dport = 255
        },
        .bin_size = 2,
        .c_size = sizeof(struct TK_plugin_TK_SET_TIME_RSP),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = TK_plugin_TK_SET_TIME_RSP_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) TK_plugin_TK_SET_TIME_RSP_parse,
        .build = (fn_build_t) TK_plugin_TK_SET_TIME_RSP_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) TK_plugin_TK_SET_TIME_RSP_parse_s,
        .build_static = (fn_build_static_t) TK_plugin_TK_SET_TIME_RSP_build_s,
        .name = "TK_plugin_TK_SET_TIME_RSP",
    #if PLD_HAVE_EXPORT
        .descr = "TK set time response",
        .data_to_json = (fn_data_to_json_t) TK_plugin_TK_SET_TIME_RSP_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = TK_PLUGIN_TK_GET_TIME_REQ_ID,
        .address = {
            .src = 255,
            .sport = 255,
            .dst = 13,
            .dport = 10
        },
        .bin_size = 1,
        .c_size = sizeof(struct TK_plugin_TK_GET_TIME_REQ),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = TK_plugin_TK_GET_TIME_REQ_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) TK_plugin_TK_GET_TIME_REQ_parse,
        .build = (fn_build_t) TK_plugin_TK_GET_TIME_REQ_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) TK_plugin_TK_GET_TIME_REQ_parse_s,
        .build_static = (fn_build_static_t) TK_plugin_TK_GET_TIME_REQ_build_s,
        .name = "TK_plugin_TK_GET_TIME_REQ",
    #if PLD_HAVE_EXPORT
        .descr = "TK get time request",
        .data_to_json = (fn_data_to_json_t) TK_plugin_TK_GET_TIME_REQ_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = TK_PLUGIN_TK_GET_TIME_RSP_ID,
        .address = {
            .src = 13,
            .sport = 10,
            .dst = 255,
            .dport = 255
        },
        .bin_size = 9,
        .c_size = sizeof(struct TK_plugin_TK_GET_TIME_RSP),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = TK_plugin_TK_GET_TIME_RSP_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) TK_plugin_TK_GET_TIME_RSP_parse,
        .build = (fn_build_t) TK_plugin_TK_GET_TIME_RSP_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) TK_plugin_TK_GET_TIME_RSP_parse_s,
        .build_static = (fn_build_static_t) TK_plugin_TK_GET_TIME_RSP_build_s,
        .name = "TK_plugin_TK_GET_TIME_RSP",
    #if PLD_HAVE_EXPORT
        .descr = "TK get time response",
        .data_to_json = (fn_data_to_json_t) TK_plugin_TK_GET_TIME_RSP_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = TK_PLUGIN_TK_SYNC_TIME_REQ_ID,
        .address = {
            .src = 255,
            .sport = 255,
            .dst = 13,
            .dport = 10
        },
        .bin_size = 10,
        .c_size = sizeof(struct TK_plugin_TK_SYNC_TIME_REQ),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = TK_plugin_TK_SYNC_TIME_REQ_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) TK_plugin_TK_SYNC_TIME_REQ_parse,
        .build = (fn_build_t) TK_plugin_TK_SYNC_TIME_REQ_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) TK_plugin_TK_SYNC_TIME_REQ_parse_s,
        .build_static = (fn_build_static_t) TK_plugin_TK_SYNC_TIME_REQ_build_s,
        .name = "TK_plugin_TK_SYNC_TIME_REQ",
    #if PLD_HAVE_EXPORT
        .descr = "TK sync time request",
        .data_to_json = (fn_data_to_json_t) TK_plugin_TK_SYNC_TIME_REQ_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = TK_PLUGIN_TK_SYNC_TIME_RSP_ID,
        .address = {
            .src = 13,
            .sport = 10,
            .dst = 255,
            .dport = 255
        },
        .bin_size = 14,
        .c_size = sizeof(struct TK_plugin_TK_SYNC_TIME_RSP),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = TK_plugin_TK_SYNC_TIME_RSP_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) TK_plugin_TK_SYNC_TIME_RSP_parse,
        .build = (fn_build_t) TK_plugin_TK_SYNC_TIME_RSP_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) TK_plugin_TK_SYNC_TIME_RSP_parse_s,
        .build_static = (fn_build_static_t) TK_plugin_TK_SYNC_TIME_RSP_build_s,
        .name = "TK_plugin_TK_SYNC_TIME_RSP",
    #if PLD_HAVE_EXPORT
        .descr = "TK sync time response",
        .data_to_json = (fn_data_to_json_t) TK_plugin_TK_SYNC_TIME_RSP_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID,
        .address = {
            .src = 255,
            .sport = 255,
            .dst = 13,
            .dport = 10
        },
        .bin_size = 10,
        .c_size = sizeof(struct TK_plugin_TK_SYNC_SLAVES_REQ),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = TK_plugin_TK_SYNC_SLAVES_REQ_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) TK_plugin_TK_SYNC_SLAVES_REQ_parse,
        .build = (fn_build_t) TK_plugin_TK_SYNC_SLAVES_REQ_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) TK_plugin_TK_SYNC_SLAVES_REQ_parse_s,
        .build_static = (fn_build_static_t) TK_plugin_TK_SYNC_SLAVES_REQ_build_s,
        .name = "TK_plugin_TK_SYNC_SLAVES_REQ",
    #if PLD_HAVE_EXPORT
        .descr = "TK sync time request",
        .data_to_json = (fn_data_to_json_t) TK_plugin_TK_SYNC_SLAVES_REQ_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID,
        .address = {
            .src = 13,
            .sport = 10,
            .dst = 255,
            .dport = 255
        },
        .bin_size = 2,
        .c_size = sizeof(struct TK_plugin_TK_SYNC_SLAVES_RSP),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = TK_plugin_TK_SYNC_SLAVES_RSP_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) TK_plugin_TK_SYNC_SLAVES_RSP_parse,
        .build = (fn_build_t) TK_plugin_TK_SYNC_SLAVES_RSP_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) TK_plugin_TK_SYNC_SLAVES_RSP_parse_s,
        .build_static = (fn_build_static_t) TK_plugin_TK_SYNC_SLAVES_RSP_build_s,
        .name = "TK_plugin_TK_SYNC_SLAVES_RSP",
    #if PLD_HAVE_EXPORT
        .descr = "TK sync time response",
        .data_to_json = (fn_data_to_json_t) TK_plugin_TK_SYNC_SLAVES_RSP_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    }
};

const struct pld_module Payloads_TK_plugin = {
    .magic = PLD_MODULE_MAGIC,
    .name = "TK_plugin",
    .specs = payload_specs,
    .start_index = 1,
    .count = 8,
};

const struct pld_spec * const PldSpec_TK_plugin_TK_SET_TIME_REQ = &payload_specs[0];
const struct pld_spec * const PldSpec_TK_plugin_TK_SET_TIME_RSP = &payload_specs[1];
const struct pld_spec * const PldSpec_TK_plugin_TK_GET_TIME_REQ = &payload_specs[2];
const struct pld_spec * const PldSpec_TK_plugin_TK_GET_TIME_RSP = &payload_specs[3];
const struct pld_spec * const PldSpec_TK_plugin_TK_SYNC_TIME_REQ = &payload_specs[4];
const struct pld_spec * const PldSpec_TK_plugin_TK_SYNC_TIME_RSP = &payload_specs[5];
const struct pld_spec * const PldSpec_TK_plugin_TK_SYNC_SLAVES_REQ = &payload_specs[6];
const struct pld_spec * const PldSpec_TK_plugin_TK_SYNC_SLAVES_RSP = &payload_specs[7];
