#!/bin/bash

# generates meson.build from the configuration and base meson files
# this is necessary because meson does not support user-defined functions
# that would be needed otherwise, and according to its maintainers,
# it will never support them. I don't like this solution either,
# but it's better than using some meson fork or copy-pasting meson.build

conf=$(cat $PWD/conf.meson.build)
base=$(cat $(dirname "$0")/base.meson.build)

cat << EOF
### This file is autogenerated, do not edit!

### BEGIN conf.meson.build ###

$conf

###  END  conf.meson.build ###

### BEGIN base.meson.build ###

$base

###  END  base.meson.build ###
EOF
