/**
 * Payload specs module TK_plugin
 * 
 * Generated by lpldgen 1.4.6
 */

#ifndef PLD_TK_PLUGIN_H
#define PLD_TK_PLUGIN_H

#include <payloads.h>

extern const struct pld_module Payloads_TK_plugin;

/**
 * Payload variants in this module
 */
enum TK_plugin_PayloadType {
    TK_PLUGIN_TK_SET_TIME_REQ_ID = 1,
    TK_PLUGIN_TK_SET_TIME_RSP_ID = 2,
    TK_PLUGIN_TK_GET_TIME_REQ_ID = 3,
    TK_PLUGIN_TK_GET_TIME_RSP_ID = 4,
    TK_PLUGIN_TK_SYNC_TIME_REQ_ID = 5,
    TK_PLUGIN_TK_SYNC_TIME_RSP_ID = 6,
    TK_PLUGIN_TK_SYNC_SLAVES_REQ_ID = 7,
    TK_PLUGIN_TK_SYNC_SLAVES_RSP_ID = 8
};

/** @defgroup spec_pointers Payload specifications
 *
 * Pointers into the spec look-up table, can be used to easily reference a pld_spec instance.
 *
 * @{
 */

extern const struct pld_spec * const PldSpec_TK_plugin_TK_SET_TIME_REQ;
extern const struct pld_spec * const PldSpec_TK_plugin_TK_SET_TIME_RSP;
extern const struct pld_spec * const PldSpec_TK_plugin_TK_GET_TIME_REQ;
extern const struct pld_spec * const PldSpec_TK_plugin_TK_GET_TIME_RSP;
extern const struct pld_spec * const PldSpec_TK_plugin_TK_SYNC_TIME_REQ;
extern const struct pld_spec * const PldSpec_TK_plugin_TK_SYNC_TIME_RSP;
extern const struct pld_spec * const PldSpec_TK_plugin_TK_SYNC_SLAVES_REQ;
extern const struct pld_spec * const PldSpec_TK_plugin_TK_SYNC_SLAVES_RSP;

/** @}*/

/** @defgroup payloads_structs Payload structs
 *
 * These structs represent payloads that can be packed to and unpacked from a binary format.
 *
 * Each struct is accompanied by its building and parsing function.
 *
 * @{
 */

/**
 * Payload "TK_SET_TIME_REQ"
 *
 * TK set time request
 */
struct TK_plugin_TK_SET_TIME_REQ {
    uint16_t pld_id; //!< Payload ID
    uint64_t time;
};

/* Associated constant values */

#define TK_PLUGIN_TK_SET_TIME_REQ_CMD_ID 0

/** sizeof(TK_SET_TIME_REQ) */
#define TK_PLUGIN_TK_SET_TIME_REQ_C_SIZE (sizeof(struct TK_plugin_TK_SET_TIME_REQ))

/** Byte size of TK_plugin_TK_SET_TIME_REQ in binary form */
#define TK_PLUGIN_TK_SET_TIME_REQ_BIN_SIZE 9

/** Payload TK_plugin_TK_SET_TIME_REQ CSP destination address */
#define TK_PLUGIN_TK_SET_TIME_REQ_DST_ADDR 13

/** Payload TK_plugin_TK_SET_TIME_REQ CSP destination port */
#define TK_PLUGIN_TK_SET_TIME_REQ_DST_PORT 10

/**
 * Payload "TK_SET_TIME_RSP"
 *
 * TK set time response
 */
struct TK_plugin_TK_SET_TIME_RSP {
    uint16_t pld_id; //!< Payload ID
    uint8_t ret_val;
};

/* Associated constant values */

#define TK_PLUGIN_TK_SET_TIME_RSP_CMD_ID 0

/** sizeof(TK_SET_TIME_RSP) */
#define TK_PLUGIN_TK_SET_TIME_RSP_C_SIZE (sizeof(struct TK_plugin_TK_SET_TIME_RSP))

/** Byte size of TK_plugin_TK_SET_TIME_RSP in binary form */
#define TK_PLUGIN_TK_SET_TIME_RSP_BIN_SIZE 2

/** Payload TK_plugin_TK_SET_TIME_RSP CSP source address */
#define TK_PLUGIN_TK_SET_TIME_RSP_SRC_ADDR 13

/** Payload TK_plugin_TK_SET_TIME_RSP CSP source port */
#define TK_PLUGIN_TK_SET_TIME_RSP_SRC_PORT 10

/**
 * Payload "TK_GET_TIME_REQ"
 *
 * TK get time request
 */
struct TK_plugin_TK_GET_TIME_REQ {
    uint16_t pld_id; //!< Payload ID
    /* empty */
};

/* Associated constant values */

#define TK_PLUGIN_TK_GET_TIME_REQ_CMD_ID 1

/** sizeof(TK_GET_TIME_REQ) */
#define TK_PLUGIN_TK_GET_TIME_REQ_C_SIZE (sizeof(struct TK_plugin_TK_GET_TIME_REQ))

/** Byte size of TK_plugin_TK_GET_TIME_REQ in binary form */
#define TK_PLUGIN_TK_GET_TIME_REQ_BIN_SIZE 1

/** Payload TK_plugin_TK_GET_TIME_REQ CSP destination address */
#define TK_PLUGIN_TK_GET_TIME_REQ_DST_ADDR 13

/** Payload TK_plugin_TK_GET_TIME_REQ CSP destination port */
#define TK_PLUGIN_TK_GET_TIME_REQ_DST_PORT 10

/**
 * Payload "TK_GET_TIME_RSP"
 *
 * TK get time response
 */
struct TK_plugin_TK_GET_TIME_RSP {
    uint16_t pld_id; //!< Payload ID
    uint64_t time;
};

/* Associated constant values */

#define TK_PLUGIN_TK_GET_TIME_RSP_CMD_ID 1

/** sizeof(TK_GET_TIME_RSP) */
#define TK_PLUGIN_TK_GET_TIME_RSP_C_SIZE (sizeof(struct TK_plugin_TK_GET_TIME_RSP))

/** Byte size of TK_plugin_TK_GET_TIME_RSP in binary form */
#define TK_PLUGIN_TK_GET_TIME_RSP_BIN_SIZE 9

/** Payload TK_plugin_TK_GET_TIME_RSP CSP source address */
#define TK_PLUGIN_TK_GET_TIME_RSP_SRC_ADDR 13

/** Payload TK_plugin_TK_GET_TIME_RSP CSP source port */
#define TK_PLUGIN_TK_GET_TIME_RSP_SRC_PORT 10

/**
 * Payload "TK_SYNC_TIME_REQ"
 *
 * TK sync time request
 */
struct TK_plugin_TK_SYNC_TIME_REQ {
    uint16_t pld_id; //!< Payload ID
    int64_t frequency;
    uint8_t flags;
};

/* Associated constant values */

#define TK_PLUGIN_TK_SYNC_TIME_REQ_CMD_ID 2

/** sizeof(TK_SYNC_TIME_REQ) */
#define TK_PLUGIN_TK_SYNC_TIME_REQ_C_SIZE (sizeof(struct TK_plugin_TK_SYNC_TIME_REQ))

/** Byte size of TK_plugin_TK_SYNC_TIME_REQ in binary form */
#define TK_PLUGIN_TK_SYNC_TIME_REQ_BIN_SIZE 10

/** Payload TK_plugin_TK_SYNC_TIME_REQ CSP destination address */
#define TK_PLUGIN_TK_SYNC_TIME_REQ_DST_ADDR 13

/** Payload TK_plugin_TK_SYNC_TIME_REQ CSP destination port */
#define TK_PLUGIN_TK_SYNC_TIME_REQ_DST_PORT 10

/**
 * Payload "TK_SYNC_TIME_RSP"
 *
 * TK sync time response
 */
struct TK_plugin_TK_SYNC_TIME_RSP {
    uint16_t pld_id; //!< Payload ID
    uint8_t error;
    uint64_t last_sync;
    uint8_t mode;
    uint8_t master_node;
    uint8_t last_failed_node;
    uint8_t ret_val;
};

/* Associated constant values */

#define TK_PLUGIN_TK_SYNC_TIME_RSP_CMD_ID 2

/** sizeof(TK_SYNC_TIME_RSP) */
#define TK_PLUGIN_TK_SYNC_TIME_RSP_C_SIZE (sizeof(struct TK_plugin_TK_SYNC_TIME_RSP))

/** Byte size of TK_plugin_TK_SYNC_TIME_RSP in binary form */
#define TK_PLUGIN_TK_SYNC_TIME_RSP_BIN_SIZE 14

/** Payload TK_plugin_TK_SYNC_TIME_RSP CSP source address */
#define TK_PLUGIN_TK_SYNC_TIME_RSP_SRC_ADDR 13

/** Payload TK_plugin_TK_SYNC_TIME_RSP CSP source port */
#define TK_PLUGIN_TK_SYNC_TIME_RSP_SRC_PORT 10

/**
 * Payload "TK_SYNC_SLAVES_REQ"
 *
 * TK sync time request
 */
struct TK_plugin_TK_SYNC_SLAVES_REQ {
    uint16_t pld_id; //!< Payload ID
    uint8_t node;
    uint64_t time;
};

/* Associated constant values */

#define TK_PLUGIN_TK_SYNC_SLAVES_REQ_CMD_ID 3

/** sizeof(TK_SYNC_SLAVES_REQ) */
#define TK_PLUGIN_TK_SYNC_SLAVES_REQ_C_SIZE (sizeof(struct TK_plugin_TK_SYNC_SLAVES_REQ))

/** Byte size of TK_plugin_TK_SYNC_SLAVES_REQ in binary form */
#define TK_PLUGIN_TK_SYNC_SLAVES_REQ_BIN_SIZE 10

/** Payload TK_plugin_TK_SYNC_SLAVES_REQ CSP destination address */
#define TK_PLUGIN_TK_SYNC_SLAVES_REQ_DST_ADDR 13

/** Payload TK_plugin_TK_SYNC_SLAVES_REQ CSP destination port */
#define TK_PLUGIN_TK_SYNC_SLAVES_REQ_DST_PORT 10

/**
 * Payload "TK_SYNC_SLAVES_RSP"
 *
 * TK sync time response
 */
struct TK_plugin_TK_SYNC_SLAVES_RSP {
    uint16_t pld_id; //!< Payload ID
    uint8_t ret_val;
};

/* Associated constant values */

#define TK_PLUGIN_TK_SYNC_SLAVES_RSP_CMD_ID 3

/** sizeof(TK_SYNC_SLAVES_RSP) */
#define TK_PLUGIN_TK_SYNC_SLAVES_RSP_C_SIZE (sizeof(struct TK_plugin_TK_SYNC_SLAVES_RSP))

/** Byte size of TK_plugin_TK_SYNC_SLAVES_RSP in binary form */
#define TK_PLUGIN_TK_SYNC_SLAVES_RSP_BIN_SIZE 2

/** Payload TK_plugin_TK_SYNC_SLAVES_RSP CSP source address */
#define TK_PLUGIN_TK_SYNC_SLAVES_RSP_SRC_ADDR 13

/** Payload TK_plugin_TK_SYNC_SLAVES_RSP CSP source port */
#define TK_PLUGIN_TK_SYNC_SLAVES_RSP_SRC_PORT 10

/** @}*/

/** @defgroup payloads_parsing Payload parsing
 *
 * Functions converting payload structs from their binary forms.
 *
 * All payload parsing functions share this signature:
 *
 * - <b>payload (in)</b> … a byte buffer to parse (e.g. received from CSP)
 * - <b>length (in)</b> … length of the payload buffer
 * - <b>alloc (in)</b> … allocator, malloc-like function used to allocate the output struct.
 *   The caller is responsible for disposing of the struct accordingly.
 * - <b>output (out)</b> … destination pointer, the parsed struct is output here
 *
 * The returned status code should be checked for errors.
 * @{
 */

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "TK_SET_TIME_REQ" payload struct. */
pld_error_t TK_plugin_TK_SET_TIME_REQ_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SET_TIME_REQ **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "TK_SET_TIME_REQ" payload struct (static version) */
pld_error_t TK_plugin_TK_SET_TIME_REQ_parse_s(const uint8_t *payload, size_t length, struct TK_plugin_TK_SET_TIME_REQ *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "TK_SET_TIME_RSP" payload struct. */
pld_error_t TK_plugin_TK_SET_TIME_RSP_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SET_TIME_RSP **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "TK_SET_TIME_RSP" payload struct (static version) */
pld_error_t TK_plugin_TK_SET_TIME_RSP_parse_s(const uint8_t *payload, size_t length, struct TK_plugin_TK_SET_TIME_RSP *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "TK_GET_TIME_REQ" payload struct. */
pld_error_t TK_plugin_TK_GET_TIME_REQ_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_GET_TIME_REQ **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "TK_GET_TIME_REQ" payload struct (static version) */
pld_error_t TK_plugin_TK_GET_TIME_REQ_parse_s(const uint8_t *payload, size_t length, struct TK_plugin_TK_GET_TIME_REQ *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "TK_GET_TIME_RSP" payload struct. */
pld_error_t TK_plugin_TK_GET_TIME_RSP_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_GET_TIME_RSP **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "TK_GET_TIME_RSP" payload struct (static version) */
pld_error_t TK_plugin_TK_GET_TIME_RSP_parse_s(const uint8_t *payload, size_t length, struct TK_plugin_TK_GET_TIME_RSP *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "TK_SYNC_TIME_REQ" payload struct. */
pld_error_t TK_plugin_TK_SYNC_TIME_REQ_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SYNC_TIME_REQ **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "TK_SYNC_TIME_REQ" payload struct (static version) */
pld_error_t TK_plugin_TK_SYNC_TIME_REQ_parse_s(const uint8_t *payload, size_t length, struct TK_plugin_TK_SYNC_TIME_REQ *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "TK_SYNC_TIME_RSP" payload struct. */
pld_error_t TK_plugin_TK_SYNC_TIME_RSP_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SYNC_TIME_RSP **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "TK_SYNC_TIME_RSP" payload struct (static version) */
pld_error_t TK_plugin_TK_SYNC_TIME_RSP_parse_s(const uint8_t *payload, size_t length, struct TK_plugin_TK_SYNC_TIME_RSP *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "TK_SYNC_SLAVES_REQ" payload struct. */
pld_error_t TK_plugin_TK_SYNC_SLAVES_REQ_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SYNC_SLAVES_REQ **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "TK_SYNC_SLAVES_REQ" payload struct (static version) */
pld_error_t TK_plugin_TK_SYNC_SLAVES_REQ_parse_s(const uint8_t *payload, size_t length, struct TK_plugin_TK_SYNC_SLAVES_REQ *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "TK_SYNC_SLAVES_RSP" payload struct. */
pld_error_t TK_plugin_TK_SYNC_SLAVES_RSP_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct TK_plugin_TK_SYNC_SLAVES_RSP **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "TK_SYNC_SLAVES_RSP" payload struct (static version) */
pld_error_t TK_plugin_TK_SYNC_SLAVES_RSP_parse_s(const uint8_t *payload, size_t length, struct TK_plugin_TK_SYNC_SLAVES_RSP *output);

/** @}*/

/** @defgroup payloads_building Payload building
 *
 * Functions converting payload structs into their binary forms.
 *
 * All payload building functions share this signature:
 *
 * - <b>data (in)</b> … the payload struct to read data from
 * - <b>alloc (in)</b> … allocator, malloc-like function called to obtain a byte buffer.
 *   The caller is responsible for disposing of the buffer accordingly.
 * - <b>output (out)</b> … destination pointer, the byte buffer is output here
 * - <b>len (out,optional)</b> … length of the output buffer is stored here (may be NULL if not needed)
 *
 * The returned status code should be checked for errors.
 * @{
 */

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "TK_SET_TIME_REQ" to its binary form. */
pld_error_t TK_plugin_TK_SET_TIME_REQ_build(const struct TK_plugin_TK_SET_TIME_REQ *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "TK_SET_TIME_REQ" to its binary form. (static version) */
pld_error_t TK_plugin_TK_SET_TIME_REQ_build_s(const struct TK_plugin_TK_SET_TIME_REQ *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "TK_SET_TIME_RSP" to its binary form. */
pld_error_t TK_plugin_TK_SET_TIME_RSP_build(const struct TK_plugin_TK_SET_TIME_RSP *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "TK_SET_TIME_RSP" to its binary form. (static version) */
pld_error_t TK_plugin_TK_SET_TIME_RSP_build_s(const struct TK_plugin_TK_SET_TIME_RSP *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "TK_GET_TIME_REQ" to its binary form. Data may be NULL. */
pld_error_t TK_plugin_TK_GET_TIME_REQ_build(const struct TK_plugin_TK_GET_TIME_REQ *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "TK_GET_TIME_REQ" to its binary form. Data may be NULL. (static version) */
pld_error_t TK_plugin_TK_GET_TIME_REQ_build_s(const struct TK_plugin_TK_GET_TIME_REQ *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "TK_GET_TIME_RSP" to its binary form. */
pld_error_t TK_plugin_TK_GET_TIME_RSP_build(const struct TK_plugin_TK_GET_TIME_RSP *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "TK_GET_TIME_RSP" to its binary form. (static version) */
pld_error_t TK_plugin_TK_GET_TIME_RSP_build_s(const struct TK_plugin_TK_GET_TIME_RSP *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "TK_SYNC_TIME_REQ" to its binary form. */
pld_error_t TK_plugin_TK_SYNC_TIME_REQ_build(const struct TK_plugin_TK_SYNC_TIME_REQ *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "TK_SYNC_TIME_REQ" to its binary form. (static version) */
pld_error_t TK_plugin_TK_SYNC_TIME_REQ_build_s(const struct TK_plugin_TK_SYNC_TIME_REQ *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "TK_SYNC_TIME_RSP" to its binary form. */
pld_error_t TK_plugin_TK_SYNC_TIME_RSP_build(const struct TK_plugin_TK_SYNC_TIME_RSP *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "TK_SYNC_TIME_RSP" to its binary form. (static version) */
pld_error_t TK_plugin_TK_SYNC_TIME_RSP_build_s(const struct TK_plugin_TK_SYNC_TIME_RSP *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "TK_SYNC_SLAVES_REQ" to its binary form. */
pld_error_t TK_plugin_TK_SYNC_SLAVES_REQ_build(const struct TK_plugin_TK_SYNC_SLAVES_REQ *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "TK_SYNC_SLAVES_REQ" to its binary form. (static version) */
pld_error_t TK_plugin_TK_SYNC_SLAVES_REQ_build_s(const struct TK_plugin_TK_SYNC_SLAVES_REQ *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "TK_SYNC_SLAVES_RSP" to its binary form. */
pld_error_t TK_plugin_TK_SYNC_SLAVES_RSP_build(const struct TK_plugin_TK_SYNC_SLAVES_RSP *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "TK_SYNC_SLAVES_RSP" to its binary form. (static version) */
pld_error_t TK_plugin_TK_SYNC_SLAVES_RSP_build_s(const struct TK_plugin_TK_SYNC_SLAVES_RSP *data, uint8_t *output, size_t capacity);

/** @}*/

#if PLD_HAVE_EXPORT
/** @defgroup payloads_building Payload building
 *
 * Functions converting payload structs into JSON.
 *
 * All payload export functions share this signature:
 *
 * - <b>data (in)</b> … the payload struct to read data from
 * - <b>style (in)</b> … JSON variant (EXPORT_JSON_DATAONLY, EXPORT_JSON_ANNOTATED)
 * - <b>output (out)</b> … destination pointer, the json is output here
 *
 * The returned status code should be checked for errors.
 * @{
 */

/** @brief Export payload struct "TK_SET_TIME_REQ" to JSON (without look-up) */
pld_error_t TK_plugin_TK_SET_TIME_REQ_to_json(const struct TK_plugin_TK_SET_TIME_REQ *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "TK_SET_TIME_RSP" to JSON (without look-up) */
pld_error_t TK_plugin_TK_SET_TIME_RSP_to_json(const struct TK_plugin_TK_SET_TIME_RSP *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "TK_GET_TIME_REQ" to JSON (without look-up) */
pld_error_t TK_plugin_TK_GET_TIME_REQ_to_json(const struct TK_plugin_TK_GET_TIME_REQ *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "TK_GET_TIME_RSP" to JSON (without look-up) */
pld_error_t TK_plugin_TK_GET_TIME_RSP_to_json(const struct TK_plugin_TK_GET_TIME_RSP *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "TK_SYNC_TIME_REQ" to JSON (without look-up) */
pld_error_t TK_plugin_TK_SYNC_TIME_REQ_to_json(const struct TK_plugin_TK_SYNC_TIME_REQ *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "TK_SYNC_TIME_RSP" to JSON (without look-up) */
pld_error_t TK_plugin_TK_SYNC_TIME_RSP_to_json(const struct TK_plugin_TK_SYNC_TIME_RSP *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "TK_SYNC_SLAVES_REQ" to JSON (without look-up) */
pld_error_t TK_plugin_TK_SYNC_SLAVES_REQ_to_json(const struct TK_plugin_TK_SYNC_SLAVES_REQ *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "TK_SYNC_SLAVES_RSP" to JSON (without look-up) */
pld_error_t TK_plugin_TK_SYNC_SLAVES_RSP_to_json(const struct TK_plugin_TK_SYNC_SLAVES_RSP *data, enum pld_export_json_style style, cJSON** output);

/** @}*/
#endif /* PLD_HAVE_EXPORT */

#endif /* PLD_TK_PLUGIN_H */
